### PR TITLE
code refactoring and fixing pylint

### PR DESCRIPTION
**Pull request by sudhirverma**

### CODE REVIEW

**Review by asa1997 — COMMENTED** [review]
@sudhirverma Is the file name change required?

**Comment by sudhirverma** [comment]
> @sudhirverma Is the file name change required?

Yes those are pylint error/warning.

**Comment by asa1997** [comment]
@sudhirverma The code for writing version details is appending the data eventhough the version is already present. It should say that version is already present. 
image

**Review by asa1997 — CHANGES_REQUESTED** [review]
@sudhirverma Please address the comment

**Comment by sudhirverma** [comment]
> @sudhirverma The code for writing version details is appending the data eventhough the version is already present. It should say that version is already present. image

@asa1997 can you check again

**Review by asa1997 — APPROVED** [review]
@sudhirverma LGTM.

**Pull request merged**
